//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hive.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GraphQL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GraphQL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hive.Resources.GraphQL", typeof(GraphQL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A collection of mods that share a similar state..
        /// </summary>
        public static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the channel..
        /// </summary>
        public static string Channel_Name {
            get {
                return ResourceManager.GetString("Channel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ID of the channel being queried for..
        /// </summary>
        public static string Channel_NameQuery {
            get {
                return ResourceManager.GetString("Channel_NameQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page number of the channel query..
        /// </summary>
        public static string Channels_QueryPage {
            get {
                return ResourceManager.GetString("Channels_QueryPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A version of the game that the current Hive instance revolves around..
        /// </summary>
        public static string GameVersion {
            get {
                return ResourceManager.GetString("GameVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DateTime in UTC at which the game version was created..
        /// </summary>
        public static string GameVersion_CreationTime {
            get {
                return ResourceManager.GetString("GameVersion_CreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the version of the game..
        /// </summary>
        public static string GameVersion_Name {
            get {
                return ResourceManager.GetString("GameVersion_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mods that are compatible with this version of the game..
        /// </summary>
        public static string GameVersion_SupportedMods {
            get {
                return ResourceManager.GetString("GameVersion_SupportedMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A named reference to a web address..
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the source of the link..
        /// </summary>
        public static string Link_Name {
            get {
                return ResourceManager.GetString("Link_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL of the link..
        /// </summary>
        public static string Link_URL {
            get {
                return ResourceManager.GetString("Link_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changelog of the mod in the language of the localized mod info..
        /// </summary>
        public static string LocalizedModInfo_Changelog {
            get {
                return ResourceManager.GetString("LocalizedModInfo_Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The credits of the mod in the language of the localized mod info..
        /// </summary>
        public static string LocalizedModInfo_Credits {
            get {
                return ResourceManager.GetString("LocalizedModInfo_Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description of the mod in the language of the localized mod info..
        /// </summary>
        public static string LocalizedModInfo_Description {
            get {
                return ResourceManager.GetString("LocalizedModInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the language..
        /// </summary>
        public static string LocalizedModInfo_Name {
            get {
                return ResourceManager.GetString("LocalizedModInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mod that the localized mod info is localizing..
        /// </summary>
        public static string LocalizedModInfo_OwningMod {
            get {
                return ResourceManager.GetString("LocalizedModInfo_OwningMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authors of the mod. This is typically everyone who has added a significant amount to the mod..
        /// </summary>
        public static string Mod_Authors {
            get {
                return ResourceManager.GetString("Mod_Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The channel that this mod is located in..
        /// </summary>
        public static string Mod_Channel {
            get {
                return ResourceManager.GetString("Mod_Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mods that are incompatible with this mod and will interfere with normal function..
        /// </summary>
        public static string Mod_Conflicts {
            get {
                return ResourceManager.GetString("Mod_Conflicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contributors of the mod. This is typically anyone who has helped with creating the mod or invidiuals who helped with translation efforts..
        /// </summary>
        public static string Mod_Contributors {
            get {
                return ResourceManager.GetString("Mod_Contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mods that are required for this mod to function properly..
        /// </summary>
        public static string Mod_Dependencies {
            get {
                return ResourceManager.GetString("Mod_Dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The download link of the mod..
        /// </summary>
        public static string Mod_DownloadLink {
            get {
                return ResourceManager.GetString("Mod_DownloadLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DateTime in UTC when the mod was last edited..
        /// </summary>
        public static string Mod_EditedAt {
            get {
                return ResourceManager.GetString("Mod_EditedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ID of the mod..
        /// </summary>
        public static string Mod_ID {
            get {
                return ResourceManager.GetString("Mod_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The links associated with this mod..
        /// </summary>
        public static string Mod_Links {
            get {
                return ResourceManager.GetString("Mod_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The localized information of the mod..
        /// </summary>
        public static string Mod_Localizations {
            get {
                return ResourceManager.GetString("Mod_Localizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The human readable ID of the mod..
        /// </summary>
        public static string Mod_ReadableID {
            get {
                return ResourceManager.GetString("Mod_ReadableID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The versions that this mod is supported for..
        /// </summary>
        public static string Mod_SupportedVersions {
            get {
                return ResourceManager.GetString("Mod_SupportedVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DateTime in UTC when the mod was originally uploaded..
        /// </summary>
        public static string Mod_UploadedAt {
            get {
                return ResourceManager.GetString("Mod_UploadedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user who uploaded the mod..
        /// </summary>
        public static string Mod_Uploader {
            get {
                return ResourceManager.GetString("Mod_Uploader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SemVer version of the mod..
        /// </summary>
        public static string Mod_Version {
            get {
                return ResourceManager.GetString("Mod_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A reference to a mod with a specific version range..
        /// </summary>
        public static string ModReference {
            get {
                return ResourceManager.GetString("ModReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ID of the mod that&apos;s being referenced..
        /// </summary>
        public static string ModReference_ModID {
            get {
                return ResourceManager.GetString("ModReference_ModID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The range of versions that the reference is corresponding to..
        /// </summary>
        public static string ModReference_VersionRange {
            get {
                return ResourceManager.GetString("ModReference_VersionRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page number of the mod query..
        /// </summary>
        public static string Mods_QueryPage {
            get {
                return ResourceManager.GetString("Mods_QueryPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Represents an individual account on this Hive instance.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication type of the user..
        /// </summary>
        public static string User_AuthenticationType {
            get {
                return ResourceManager.GetString("User_AuthenticationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ID of the user..
        /// </summary>
        public static string User_ID {
            get {
                return ResourceManager.GetString("User_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether or not the user is authenticated..
        /// </summary>
        public static string User_IsAuthenticated {
            get {
                return ResourceManager.GetString("User_IsAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the user..
        /// </summary>
        public static string User_Name {
            get {
                return ResourceManager.GetString("User_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username of the user..
        /// </summary>
        public static string User_Username {
            get {
                return ResourceManager.GetString("User_Username", resourceCulture);
            }
        }
    }
}
