//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hive.Plugins.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hive.Plugins.Resources.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target method takes Expressions but does not return an Expression type.
        /// </summary>
        internal static string AggregateWith_AlmostExpressionAggregator {
            get {
                return ResourceManager.GetString("AggregateWith_AlmostExpressionAggregator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find agggregator on {0} with name {1}.
        /// </summary>
        internal static string AggregateWith_NoSuchAggregator {
            get {
                return ResourceManager.GetString("AggregateWith_NoSuchAggregator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A foreach loop can only take IEnumerable and IEnumerable&lt;T&gt;.
        /// </summary>
        internal static string Foreach_EnumerableInvalid {
            get {
                return ResourceManager.GetString("Foreach_EnumerableInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerator for enumerable is not an enumerator.
        /// </summary>
        internal static string Foreach_EnumeratorNotEnumerator {
            get {
                return ResourceManager.GetString("Foreach_EnumeratorNotEnumerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerator for enumerable does not have a Current property.
        /// </summary>
        internal static string Foreach_EnumeratorWithoutCurrent {
            get {
                return ResourceManager.GetString("Foreach_EnumeratorWithoutCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop variable cannot be assigned from enumeration type {0}.
        /// </summary>
        internal static string Foreach_IncorrectLoopVariable {
            get {
                return ResourceManager.GetString("Foreach_IncorrectLoopVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerable has no public member GetEnumerator().
        /// </summary>
        internal static string Foreach_NoPublicGetEnumerator {
            get {
                return ResourceManager.GetString("Foreach_NoPublicGetEnumerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregated interfaces must be marked [Aggregable]!.
        /// </summary>
        internal static string Generator_AggregateMustBeAggregable {
            get {
                return ResourceManager.GetString("Generator_AggregateMustBeAggregable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute {0} invalid on parameter {1}.
        /// </summary>
        internal static string Generator_AttributeInvalidOn {
            get {
                return ResourceManager.GetString("Generator_AttributeInvalidOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregated instances can only be generated from interfaces!.
        /// </summary>
        internal static string Generator_CanOnlyAggregateInterfaces {
            get {
                return ResourceManager.GetString("Generator_CanOnlyAggregateInterfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On parameter {1}, invalid argument index {0}.
        /// </summary>
        internal static string Generator_InvalidParameterIndex {
            get {
                return ResourceManager.GetString("Generator_InvalidParameterIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0} cannot have both {1} and {2}.
        /// </summary>
        internal static string Generator_MethodMayHaveOneOf {
            get {
                return ResourceManager.GetString("Generator_MethodMayHaveOneOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0} must return a boolean to use {1}.
        /// </summary>
        internal static string Generator_MethodMustReturnBoolToUse {
            get {
                return ResourceManager.GetString("Generator_MethodMustReturnBoolToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method {0} must return a nullable type to use {1}.
        /// </summary>
        internal static string Generator_MethodMustReturnNullableToUse {
            get {
                return ResourceManager.GetString("Generator_MethodMustReturnNullableToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target out parameter not compatible with parameter {0}.
        /// </summary>
        internal static string Generator_OutParamNotCompatible {
            get {
                return ResourceManager.GetString("Generator_OutParamNotCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} cannot take return value.
        /// </summary>
        internal static string Generator_ParameterCannotTakeReturn {
            get {
                return ResourceManager.GetString("Generator_ParameterCannotTakeReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter index {0} is not an out parameter.
        /// </summary>
        internal static string Generator_ParameterNotOutParam {
            get {
                return ResourceManager.GetString("Generator_ParameterNotOutParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown input specifying attribute {0}.
        /// </summary>
        internal static string Generator_UnknownInputAttribute {
            get {
                return ResourceManager.GetString("Generator_UnknownInputAttribute", resourceCulture);
            }
        }
    }
}
